{
 "title": "Dashboard 1 — Database Exporter (PostgreSQL / MySQL)",
 "time": { "from": "2025-11-06T19:14:48.429Z", "to": "2025-11-07T01:36:46.632Z" },
 "panels": [
  {
   "title": "Replication Lag (sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops/s" } },
   "targets": [
    { "expr": "pg_replication_lag_seconds\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connection Limit",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_connection_limit{datname=\"demo\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exporter Health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_exporter_scrapes_total\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Users & Privileges",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_settings_max_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Query Throughput (QPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit[5m]) + rate(pg_stat_database_xact_rollback[5m])\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Writes per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted[5m]) \r\n+ rate(pg_stat_database_tup_updated[5m]) \r\n+ rate(pg_stat_database_tup_deleted[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read & Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_read[5m]) + rate(pg_stat_database_blks_hit[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Size (GB)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "gigabytes (GB)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes / 1024 / 1024 / 1024\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Up Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_up\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"demo\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}